[[permission]]
identifier = "allow-app-commands"
description = "Enables app info and updater install commands."
commands.allow = [
    "get_app_info",
    "webview_gpu_disabled",
    "relaunch_app",
    "download_and_install_update",
]
