export const IPC_COMMANDS = {
  openSettings: "open_settings",
  openSessionInOverlay: "open_session_in_overlay",
  openSessionInWorkbench: "open_session_in_workbench",
  showInteractionNotification: "show_interaction_notification",
  dismissInteractionNotification: "dismiss_interaction_notification",
  setWindowSessionView: "set_window_session_view",
  hideOverlay: "hide_overlay_window",
  minimizeOverlay: "minimize_overlay_window",
  closeOverlay: "close_overlay_window",
  exitApp: "exit_app",
  getAppSettings: "get_app_settings",
  setAppSettings: "set_app_settings",
  geminiAuthStatus: "gemini_auth_status",
  geminiOauthLogin: "gemini_oauth_login",
  geminiOauthCancelLogin: "gemini_oauth_cancel_login",
  geminiOauthLogout: "gemini_oauth_logout",
  geminiImportClientSecrets: "gemini_import_client_secrets",
  getAppInfo: "get_app_info",
  webviewGpuDisabled: "webview_gpu_disabled",
  relaunchApp: "relaunch_app",
  buildCodeDiff: "build_code_diff",
  chat: "chat",
  chatCancel: "chat_cancel",
  agentDebugSnapshot: "agent_debug_snapshot",
  chatHistory: "chat_history",
  listChatSessions: "list_chat_sessions",
  listArchivedChatSessions: "list_archived_chat_sessions",
  listChatModels: "list_chat_models",
  listCustomProviderModels: "list_custom_provider_models",
  getContextUsage: "get_context_usage",
  getTokenUsageReport: "get_token_usage_report",
  getEnvironmentContext: "get_environment_context",
  setOverlayChatMode: "set_overlay_chat_mode_command",
  setOverlayPopupOpen: "set_overlay_popup_open_command",
  takeOverlayContext: "take_overlay_context",
  respondAskUser: "respond_ask_user",
  respondPathPermission: "respond_path_permission",
  respondToolApproval: "respond_tool_approval",
  setPlanMode: "set_plan_mode",
  getPlanMode: "get_plan_mode",
  listCheckpoints: "list_checkpoints",
  rewindSession: "rewind_session",
  branchChatSession: "branch_chat_session",
  setChatSessionTitle: "set_chat_session_title",
  regenerateChatSessionTitle: "regenerate_chat_session_title",
  revealInExplorer: "reveal_in_explorer",
  openInDefaultApp: "open_in_default_app",
} as const;

export const IPC_EVENTS = {
  agentEvent: "agent-event",
  agentDebugEvent: "agent-debug-event",
  overlayShown: "overlay-shown",
  overlayHidden: "overlay-hidden",
  settingsChanged: "settings-changed",
  chatStarted: "chat-started",
  chatDelta: "chat-delta",
  chatReasoning: "chat-reasoning",
  chatStatus: "chat-status",
  chatUserContent: "chat-user-content",
  chatFinished: "chat-finished",
  chatTokenUsage: "chat-token-usage",
  chatSessionTitleUpdated: "chat-session-title-updated",
  chatError: "chat-error",
  chatContextNotice: "chat-context-notice",
  contextCaptured: "context-captured",
  askUser: "ask-user",
  pathPermission: "path-permission",
  toolApproval: "tool-approval",
  interactionResolved: "interaction-resolved",
  planModeChanged: "plan-mode-changed",
  toolStarted: "tool-started",
  toolFinished: "tool-finished",
  taskListUpdated: "task-list-updated",
  fileOffer: "file-offer",
  urlOffer: "url-offer",
} as const;

export type IpcCommand = (typeof IPC_COMMANDS)[keyof typeof IPC_COMMANDS];
export type IpcEvent = (typeof IPC_EVENTS)[keyof typeof IPC_EVENTS];
